export const FUND_DETAILS_REQUEST = 'FUND_DETAILS_REQUEST'
export const FUND_DETAILS_SUCCESS = 'FUND_DETAILS_SUCCESS'
export const FUND_DETAILS_FAIL = 'FUND_DETAILS_FAIL'

export const FUND_LIST_TRANSACTIONS_REQUEST = 'FUND_LIST_TRANSACTIONS_REQUEST'
export const FUND_LIST_TRANSACTIONS_SUCCESS = 'FUND_LIST_TRANSACTIONS_SUCCESS'
export const FUND_LIST_TRANSACTIONS_FAIL = 'FUND_LIST_TRANSACTIONS_FAIL'

export const FUND_ADD_TRANSACTION_REQUEST = 'FUND_ADD_TRANSACTION_REQUEST'
export const FUND_ADD_TRANSACTION_SUCCESS = 'FUND_ADD_TRANSACTION_SUCCESS'
export const FUND_ADD_TRANSACTION_FAIL = 'FUND_ADD_TRANSACTION_FAIL'
export const FUND_ADD_TRANSACTION_RESET = 'FUND_ADD_TRANSACTION_RESET'
