export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST'
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS'
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL'

export const PLAYER_DETAILS_REQUEST = 'PLAYER_DETAILS_REQUEST'
export const PLAYER_DETAILS_SUCCESS = 'PLAYER_DETAILS_SUCCESS'
export const PLAYER_DETAILS_FAIL = 'PLAYER_DETAILS_FAIL'

export const PLAYER_UPDATE_REQUEST = 'PLAYER_UPDATE_REQUEST'
export const PLAYER_UPDATE_SUCCESS = 'PLAYER_UPDATE_SUCCESS'
export const PLAYER_UPDATE_FAIL = 'PLAYER_UPDATE_FAIL'
export const PLAYER_UPDATE_RESET = 'PLAYER_UPDATE_RESET'

export const PLAYER_REGISTER_REQUEST = 'PLAYER_REGISTER_REQUEST'
export const PLAYER_REGISTER_SUCCESS = 'PLAYER_REGISTER_SUCCESS'
export const PLAYER_REGISTER_FAIL = 'PLAYER_REGISTER_FAIL'
export const PLAYER_REGISTER_RESET = 'PLAYER_REGISTER_RESET'

export const PLAYER_DELETE_REQUEST = 'PLAYER_DELETE_REQUEST'
export const PLAYER_DELETE_SUCCESS = 'PLAYER_DELETE_SUCCESS'
export const PLAYER_DELETE_FAIL = 'PLAYER_DELETE_FAIL'
export const PLAYER_DELETE_RESET = 'PLAYER_DELETE_RESET'

export const PLAYER_ADD_TRANSACTION_REQUEST = 'PLAYER_ADD_TRANSACTION_REQUEST'
export const PLAYER_ADD_TRANSACTION_SUCCESS = 'PLAYER_ADD_TRANSACTION_SUCCESS'
export const PLAYER_ADD_TRANSACTION_FAIL = 'PLAYER_ADD_TRANSACTION_FAIL'
export const PLAYER_ADD_TRANSACTION_RESET = 'PLAYER_ADD_TRANSACTION_RESET'
