export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST'
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS'
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL'

export const PLAYER_DETAILS_REQUEST = 'PLAYER_DETAILS_REQUEST'
export const PLAYER_DETAILS_SUCCESS = 'PLAYER_DETAILS_SUCCESS'
export const PLAYER_DETAILS_FAIL = 'PLAYER_DETAILS_FAIL'

export const PLAYER_UPDATE_REQUEST = 'PLAYER_UPDATE_REQUEST'
export const PLAYER_UPDATE_SUCCESS = 'PLAYER_UPDATE_SUCCESS'
export const PLAYER_UPDATE_FAIL = 'PLAYER_UPDATE_FAIL'
export const PLAYER_UPDATE_RESET = 'PLAYER_UPDATE_RESET'
