export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL'

export const PROFILE_CHANGE_PASSWORD_REQUEST = 'PROFILE_CHANGE_PASSWORD_REQUEST'
export const PROFILE_CHANGE_PASSWORD_SUCCESS = 'PROFILE_CHANGE_PASSWORD_SUCCESS'
export const PROFILE_CHANGE_PASSWORD_FAIL = 'PROFILE_CHANGE_PASSWORD_FAIL'
export const PROFILE_CHANGE_PASSWORD_RESET = 'PROFILE_CHANGE_PASSWORD_RESET'
