export const PLAYER_ROOM_LIST_REQUEST = 'PLAYER_ROOM_LIST_REQUEST'
export const PLAYER_ROOM_LIST_SUCCESS = 'PLAYER_ROOM_LIST_SUCCESS'
export const PLAYER_ROOM_LIST_FAIL = 'PLAYER_ROOM_LIST_FAIL'

export const PLAYER_ROOM_DETAILS_REQUEST = 'PLAYER_ROOM_DETAILS_REQUEST'
export const PLAYER_ROOM_DETAILS_SUCCESS = 'PLAYER_ROOM_DETAILS_SUCCESS'
export const PLAYER_ROOM_DETAILS_FAIL = 'PLAYER_ROOM_DETAILS_FAIL'

export const PLAYER_ROOM_UPDATE_REQUEST = 'PLAYER_ROOM_UPDATE_REQUEST'
export const PLAYER_ROOM_UPDATE_SUCCESS = 'PLAYER_ROOM_UPDATE_SUCCESS'
export const PLAYER_ROOM_UPDATE_FAIL = 'PLAYER_ROOM_UPDATE_FAIL'
export const PLAYER_ROOM_UPDATE_RESET = 'PLAYER_ROOM_UPDATE_RESET'
