export const SESSION_LIST_REQUEST = 'SESSION_LIST_REQUEST'
export const SESSION_LIST_SUCCESS = 'SESSION_LIST_SUCCESS'
export const SESSION_LIST_FAIL = 'SESSION_LIST_FAIL'

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST'
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS'
export const SESSION_DETAILS_FAIL = 'SESSION_DETAILS_FAIL'

export const SESSION_CREATE_REQUEST = 'SESSION_CREATE_REQUEST'
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS'
export const SESSION_CREATE_FAIL = 'SESSION_CREATE_FAIL'
export const SESSION_CREATE_RESET = 'SESSION_CREATE_RESET'

export const ROOM_SESSION_CREATE_REQUEST = 'ROOM_SESSION_CREATE_REQUEST'
export const ROOM_SESSION_CREATE_SUCCESS = 'ROOM_SESSION_CREATE_SUCCESS'
export const ROOM_SESSION_CREATE_FAIL = 'ROOM_SESSION_CREATE_FAIL'
export const ROOM_SESSION_CREATE_RESET = 'ROOM_SESSION_CREATE_RESET'
