export const ROOM_TRANSACTION_LIST_REQUEST = 'ROOM_TRANSACTION_LIST_REQUEST'
export const ROOM_TRANSACTION_LIST_SUCCESS = 'ROOM_TRANSACTION_LIST_SUCCESS'
export const ROOM_TRANSACTION_LIST_FAIL = 'ROOM_TRANSACTION_LIST_FAIL'

export const PLAYER_TRANSACTION_LIST_REQUEST = 'PLAYER_TRANSACTION_LIST_REQUEST'
export const PLAYER_TRANSACTION_LIST_SUCCESS = 'PLAYER_TRANSACTION_LIST_SUCCESS'
export const PLAYER_TRANSACTION_LIST_FAIL = 'PLAYER_TRANSACTION_LIST_FAIL'

export const ROOM_TRANSACTION_ADD_REQUEST = 'ROOM_TRANSACTION_ADD_REQUEST'
export const ROOM_TRANSACTION_ADD_SUCCESS = 'ROOM_TRANSACTION_ADD_SUCCESS'
export const ROOM_TRANSACTION_ADD_FAIL = 'ROOM_TRANSACTION_ADD_FAIL'
export const ROOM_TRANSACTION_ADD_RESET = 'ROOM_TRANSACTION_ADD_RESET'
